### ISSUE TITLE
输入检测

### ISSUE THREAD

**Issue by Heaveeeen** [MythoniaTeam/NavalBattleTBS#1]
我打算在input.js中用onkeydown和onkeyup事件来检测玩家的键盘输入，但我不知道我需要检测多少个按键，于是我姑且为keyState预留了256个位置：
```
var keyState = [];
//存储每个按键的状态
//等于0为静息状态
//大于0为正在被按下，数值为按下持续的帧数
//小于0为被松开的一瞬间，数值为松开前按下持续的帧数
for (var i = 0; i < 256; i++) {
    keyState.push(0);
};
```
另外我记得keyboard事件传入的keyCode貌似根本无法用于检测shift等没有对应字符的特殊键位，如果是这样的话，我如何才能检测这些特殊键位？在这255个位置中有能够安全地用于保存这些特殊键位的位置吗？

**Comment by Heaveeeen** [comment]
我又做了一些尝试，这些问题基本上都解决了，包括shift、ctrl、enter等特殊键位在内的所有按键都可以被正常检测到。但现在我又遇到了两个非常令我头疼的问题：

* onkeydown事件的机制问题，长按某个按键会触发连点（这个问题很严重）
* 所有的按键事件所得到的keyCode都会传入到一个缓冲列表并在下一帧时被放入keyState中，这样可以大大提升按键检测的稳定性，但按键似乎总是会有明显的延迟（但我做的不是动作游戏，这个问题倒也可以忍受，作为一个程序员不要太苛求修复那些没必要修复的bug）

**Comment by Tinellie** [comment]
好（）

**Comment by Tinellie** [comment]
> 我又做了一些尝试，这些问题基本上都解决了，包括shift、ctrl、enter等特殊键位在内的所有按键都可以被正常检测到。但现在我又遇到了两个非常令我头疼的问题：
> 
> * onkeydown事件的机制问题，长按某个按键会触发连点（这个问题很严重）
> * 所有的按键事件所得到的keyCode都会传入到一个缓冲列表并在下一帧时被放入keyState中，这样可以大大提升按键检测的稳定性，但按键似乎总是会有明显的延迟（但我做的不是动作游戏，这个问题倒也可以忍受，作为一个程序员不要太苛求修复那些没必要修复的bug）

(

**Comment by Heaveeeen** [comment]
新的问题又出现了

onkeydown貌似有一个防止用户滚键盘的机制（我并不清楚其内部原理），导致有时并不能准确地检测用户所按下的按键……

幸运的是，这个机制看起来不会对我的成品产生什么负面影响

**Comment by Heaveeeen** [comment]
我是不是手滑点了什么close和reopen之类的东西了……这其实是我第一次使用issue

**Comment by Tinellie** [comment]
你知道close和reopen是啥吗（），你刚才已经把这个issue关闭了，现在又重开了

**Comment by Heaveeeen** [comment]
@Tinellie 我刚才不知道，但从字面意义来看我能猜出来这东西是干什么用的

**Comment by Tinellie** [comment]
另外commit可以绑定issue，在commit标题上加上 #xxx 就可以（）

**Comment by Tinellie** [comment]
commit也可以这样
> [xxx]: title, closed #1
closed, close, closes, fixed, fix, fixes, resolved, resolve, resolves 都可以(

**Comment by Heaveeeen** [comment]
问题已经解决了。没想到解决方案居然这么简单：我只是在按键被按住时忽略onkeydown事件就忽略自动连点的效果了
